---
title: "Team 11 Solution"
author: "Team11"
date: "4/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importing packages

```{r, message=FALSE,warning=FALSE}
rm(list=ls())
library(tidyverse)
library(dplyr)
library(lubridate)
library(ggplot2)
library(Matrix)
library(Metrics)
library(glmnet)
```

## Load data

```{r, message=FALSE,warning=FALSE}
#set.seed(1)
#histdata <- read.csv("historical_transactions.csv")
#newdata <- read.csv("new_merchant_transactions.csv")
#sampel.down.hist <- sample(nrow(histdata), nrow(histdata) * .1)
#sampel.down.new <- sample(nrow(newdata), nrow(newdata) * .1)
#histdata <- histdata[sampel.down.hist, ]
#newdata <- newdata[sampel.down.new, ]
#write.csv(histdata, file = "historical_transactions_small.csv",row.names=TRUE)
#write.csv(newdata, file = "new_merchant_transactions_small.csv",row.names=TRUE)

train <- read_csv("train.csv")
test <- read_csv("test.csv")
histdata <- read_csv("historical_transactions_small.csv")
newdata <- read_csv("new_merchant_transactions_small.csv")
merchants <- read_csv("merchants.csv")
```

## Explore data
```{r, message=FALSE,warning=FALSE}
dim(train)
head(train)
glimpse(train)

head(test)

dim(histdata)
head(histdata)
glimpse(histdata)

dim(newdata)
head(newdata)

dim(merchants)
head(merchants)

# train target
summary(train$target)
# plot distribution
hist(train$target, breaks=100, freq=FALSE, col="lightgray", main="Train_target Distribution")

#---------Team 11 Original------------
train <- filter(train, target > (-30))
#---------Team 11 Original------------

# train feature
table(train$feature_1)
table(train$feature_2)
table(train$feature_3)

head(histdata)

table(histdata$authorized_flag)
prop.table(table(histdata$authorized_flag))

table(histdata$category_1)
prop.table(table(histdata$category_1))

table(histdata$category_2)
prop.table(table(histdata$category_2))

table(histdata$category_3)
prop.table(table(histdata$category_3))

summary(histdata$purchase_amount)

summary(histdata$month_lag)

glimpse(histdata)
```

## Featrue Selection
### historical transaction data
```{r, message=FALSE,warning=FALSE}
# histdata category
hist_cat1 <- histdata %>% group_by(card_id,category_1) %>% 
summarize(count=n())%>%
spread(key=category_1, value=count)

hist_cat2 <- histdata %>% group_by(card_id,category_2) %>% 
summarize(count=n())%>%
spread(key=category_2, value=count)

hist_cat3 <- histdata %>% group_by(card_id,category_3) %>% 
summarize(count=n())%>%
spread(key=category_3, value=count)

#count unique categories and merchant
hist_summary2 <- histdata %>% group_by(card_id)%>%
                summarise_at(vars(starts_with("merchant_"),starts_with("category")), n_distinct, na.rm = TRUE)

# purchase term, how many days between each transaction.
hist_summary3 <- histdata %>% group_by(card_id)%>%
                summarize(no_trans=n(), 
                          pur_term = as.integer(diff(range(purchase_date))),
                          #---------Team 11 Changed------------
                          #avg_term = as.integer(mean(abs(diff(order(purchase_date)))))
                          avg_term = as.integer(mean(abs(difftime(sort(purchase_date), lag(sort(purchase_date),1), units='days')), na.rm=TRUE))
                          #---------Team 11 Changed------------
                         )

fn <- funs(sum, mean, min, max, sd, n_distinct, .args = list(na.rm = TRUE))
histdata$authorized_flag <- ifelse(histdata$authorized_flag == "Y",1,0)

hist_summary <- histdata %>%
    group_by(card_id) %>% 
    select(c("card_id","purchase_amount","month_lag","installments","authorized_flag")) %>%
    summarize_all(fn) %>%
    left_join(hist_summary2,by="card_id") %>%
    left_join(hist_summary3,by="card_id") %>%
    left_join(hist_cat1,by="card_id") %>%
    left_join(hist_cat2[,-7],by="card_id") %>%
    left_join(hist_cat3[,-5],by="card_id") 

#head(hist_summary)                          
```

### new merchants transaction data
```{r, message=FALSE,warning=FALSE}
# newdata category
new_cat1 <- newdata %>% group_by(card_id,category_1) %>% 
summarize(count=n())%>%
spread(key=category_1, value=count)

new_cat2 <- newdata %>% group_by(card_id,category_2) %>% 
summarize(count=n())%>%
spread(key=category_2, value=count)

new_cat3 <- newdata %>% group_by(card_id,category_3) %>% 
summarize(count=n())%>%
spread(key=category_3, value=count)

# rename columns
colnames(new_cat1) <- c("card_id","new_N", "new_Y")
colnames(new_cat2) <- c("card_id","new1", "new2","new3","new4","new5","na")
colnames(new_cat3) <- c("card_id","new_A", "new_B", "new_C", "na")

# merge new transaction & merchants data
new_merge <- newdata %>%
  left_join(merchants, by="merchant_id",suffix = c("_new", "_m"))

new_summary2 <- new_merge %>% group_by(card_id)%>%
                summarise_at(vars(starts_with("merchant_"),starts_with("category")), n_distinct, na.rm = TRUE)

new_summary3 <- new_merge %>%
  group_by(card_id) %>% 
  summarise(
      new_no_trans=n(), 
      new_pur_term = as.integer(diff(range(purchase_date))),
      
      #---------Team 11 Changed------------
      #new_avg_term = as.integer(mean(abs(diff(order(purchase_date)))))
      new_avg_term = as.integer(mean(abs(difftime(sort(purchase_date), lag(sort(purchase_date),1), units='days')), na.rm=TRUE))
      #---------Team 11 Changed------------
  )

new_merge$authorized_flag <- ifelse(new_merge$authorized_flag == "Y",1,0)

new_summary <- new_merge %>%
    group_by(card_id) %>% 
    select(c("card_id","purchase_amount","month_lag","installments","authorized_flag","avg_purchases_lag3","avg_purchases_lag6","avg_purchases_lag12")) %>%
    summarize_all(fn) %>%
    left_join(new_summary2,by="card_id") %>%
    left_join(new_summary3,by="card_id") %>%
    left_join(new_cat1, by="card_id") %>%
    left_join(new_cat2[,-7],by="card_id") %>%
    left_join(new_cat3[,-5],by="card_id") 

#head(new_summary)
```


### training data
```{r, message=FALSE,warning=FALSE}
train_data <- train %>% 
    mutate(first_active_month = ymd(first_active_month, truncated = 1),
         howlong = as.integer(ymd("2018-02-01") - first_active_month)) %>%
    left_join(hist_summary, by="card_id") %>%
    left_join(new_summary,by="card_id",suffix = c("", "_new"))

head(train_data)

# fill 0 to NA 
train_data[is.na(train_data)] <- 0
head(train_data)
dim(train_data)

data <- train_data[,-c(1,2)]
```

# Train/Test
```{r, message=FALSE,warning=FALSE}
library(caret)
set.seed(1)
divideData<-createDataPartition(data$target, p=.8, list=FALSE)

data <- data[divideData,]
test.final <- data[-divideData,]
```

# XGBoost Model
```{r, message=FALSE,warning=FALSE}
library(xgboost)

params <- list(objective = "reg:linear",
          booster = "gbtree",
          eval_metric = "rmse",
          nthread = 4,
          eta = 0.01,
          max_depth = 8,
          min_child_weight = 5,
          gamma = 1,
          subsample = 0.8,
          colsample_bytree = 0.7,
          colsample_bylevel = 0.6,
          alpha = 0.1,
          lambda = 5)

data_train_final <- as.matrix(data[,-4])
dtrain_final <- xgb.DMatrix(data = data_train_final, label = data$target)

data_test_final <- as.matrix(test.final[,-4])
dtest_final <- xgb.DMatrix(data = data_test_final)
set.seed(1)
xgb_model <- xgboost(params = params, 
                       data=dtrain_final, 
                       nrounds = 1000, 
                       print_every_n = 100, 
                       early_stopping_rounds = 50)
```

```{r, message=FALSE,warning=FALSE}
# prediction
preds <- predict(xgb_model, newdata = dtest_final) 
summary(preds)

rmse <- sqrt(mean((preds-test.final$target)^2))
cat("Test RMSE:",rmse)
r <- cbind(actual= test.final$target, predicted = format(preds, scientific=F))
head(r)
plot(r)
```

```{r, message=FALSE,warning=FALSE}
#importance <- xgb.importance(feature_names = colnames(dtrain_final), model = xgb_model)
#importance 

#importance%>% 
#ggplot()+ geom_col(aes(x=reorder(Feature, Gain), y=Gain), fill ="blue") + coord_flip() + 
#labs(title = "Most important features", x="Feature")+ theme_minimal()
```

# XGBoost with selected 20 features
```{r, message=FALSE,warning=FALSE}
#SmallData Test
smalldata<- cbind(data$howlong, data$month_lag_min, data$Y, data$pur_term, data$authorized_flag_mean, data$purchase_amount_max_new, data$month_lag_mean, data$month_lag_sd, data$month_lag_n_distinct, data$month_lag_mean_new, data$authorized_flag_sd, data$B, data$purchase_amount_sd_new, data$purchase_amount_sum, data$new_pur_term, data$purchase_amount_mean, data$installments_sum, data$purchase_amount_mean_new, target=data$target)

smalldata_test<- cbind(test.final$howlong, test.final$month_lag_min, test.final$Y, test.final$pur_term, test.final$authorized_flag_mean, test.final$purchase_amount_max_new, test.final$month_lag_mean, test.final$month_lag_sd, test.final$month_lag_n_distinct, test.final$month_lag_mean_new, test.final$authorized_flag_sd, test.final$B, test.final$purchase_amount_sd_new, test.final$purchase_amount_sum, test.final$new_pur_term, test.final$purchase_amount_mean, test.final$installments_sum, test.final$purchase_amount_mean_new, target = test.final$target)

```

```{r, message=FALSE,warning=FALSE}
smalldata_train_final <- as.matrix(smalldata[,-19])
smalldtrain_final <- xgb.DMatrix(data = smalldata_train_final, label = smalldata[,19])

smalldata_test_final <- as.matrix(smalldata_test[,-19])
smalldtest_final <- xgb.DMatrix(data = smalldata_test_final)
set.seed(1)
xgb_model_small <- xgboost(params = params, 
                       data=smalldtrain_final, 
                       nrounds = 1000, 
                       print_every_n = 100, 
                       early_stopping_rounds = 50)
```

```{r, message=FALSE,warning=FALSE}
# prediction
preds_small <- predict(xgb_model_small, newdata = smalldtest_final) 
summary(preds_small)

rmse <- sqrt(mean((preds_small-smalldata_test[,19])^2))
cat("Test RMSE:",rmse)
r <- cbind(actual= smalldata_test[,19], predicted = format(preds_small, scientific=F))
head(r)
plot(r)
```

# Lasso with 111 features
```{r, message=FALSE,warning=FALSE}
set.seed(1)
data_lasso <- data[,!(colnames(data) %in% c("authorized_flag_max","avg_purchases_lag3_min","avg_purchases_lag6_min",
                                        "avg_purchases_lag12_min","avg_purchases_lag3_max","avg_purchases_lag6_max",
                                        "avg_purchases_lag12_max","authorized_flag_sd_new"))]

test_lasso <- test.final[,!(colnames(test.final) %in% c("authorized_flag_max","avg_purchases_lag3_min","avg_purchases_lag6_min",
                                        "avg_purchases_lag12_min","avg_purchases_lag3_max","avg_purchases_lag6_max",
                                        "avg_purchases_lag12_max","authorized_flag_sd_new"))]


X <-model.matrix(target~.,data_lasso)[,-1]
X.test <-model.matrix(target~.,test_lasso)[,-1]
Y <-data$target
mod.lasso <- glmnet(X, Y, alpha = 1)
cv.out.lasso <- cv.glmnet(X, Y, alpha=1, nfolds=12)
plot(cv.out.lasso)
(bestlam <- cv.out.lasso$lambda.min)
#train RMSE
sqrt(cv.out.lasso$cvm[cv.out.lasso$lambda == cv.out.lasso$lambda.1se])

lasso.pred <- predict(mod.lasso, s=bestlam, newx = X.test)
library(mltools)
rmse(lasso.pred, test.final$target)
```

